coverage:
  precision: 2
  round: down
  range: "100...100"
  status:
    project: true
    patch: true
    changes: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: yes

ignore:
  - 'tests/*'
